// Invented demo prices in PHP per kilogram. These are not market observations.
// The product list is a small sample relevant to Davao del Sur markets, not an exhaustive catalog.
export const demoProducts = [
  { name: 'Banana (Saba)', category: 'fruit', previous: 55, price: 58 },
  { name: 'Banana (Lakatan)', category: 'fruit', previous: 85, price: 82 },
  { name: 'Mango', category: 'fruit', previous: 180, price: 195 },
  { name: 'Durian', category: 'fruit', previous: 145, price: 138 },
  { name: 'Pineapple', category: 'fruit', previous: 80, price: 84 },
  { name: 'Pomelo', category: 'fruit', previous: 130, price: 125 },
  { name: 'Papaya', category: 'fruit', previous: 65, price: 68 },
  { name: 'Calamansi', category: 'fruit', previous: 120, price: 115 },
  { name: 'Jackfruit (Langka)', category: 'fruit', previous: 70, price: 75 },
  { name: 'Rambutan', category: 'fruit', previous: 150, price: 142 },
  { name: 'Tomato (Kamatis)', category: 'vegetable', previous: 90, price: 98 },
  { name: 'Eggplant (Talong)', category: 'vegetable', previous: 85, price: 80 },
  { name: 'Ampalaya', category: 'vegetable', previous: 115, price: 120 },
  { name: 'Okra', category: 'vegetable', previous: 75, price: 72 },
  { name: 'String Beans (Sitaw)', category: 'vegetable', previous: 95, price: 100 },
  { name: 'Cabbage (Repolyo)', category: 'vegetable', previous: 105, price: 99 },
  { name: 'Pechay', category: 'vegetable', previous: 90, price: 94 },
  { name: 'Squash (Kalabasa)', category: 'vegetable', previous: 55, price: 52 },
  { name: 'Carrot', category: 'vegetable', previous: 125, price: 130 },
  { name: 'Potato', category: 'vegetable', previous: 110, price: 106 },
  { name: 'Sweet Potato (Camote)', category: 'vegetable', previous: 65, price: 68 },
  { name: 'Cassava (Balanghoy)', category: 'vegetable', previous: 50, price: 48 },
  { name: 'Cucumber (Pipino)', category: 'vegetable', previous: 70, price: 73 },
  { name: 'Chayote (Sayote)', category: 'vegetable', previous: 62, price: 60 },
  { name: 'Ginger (Luya)', category: 'spice', previous: 175, price: 185 },
  { name: 'Red Onion (Bombay)', category: 'spice', previous: 160, price: 150 },
  { name: 'Garlic (Ahos)', category: 'spice', previous: 190, price: 198 },
  { name: 'Chili (Siling Labuyo)', category: 'spice', previous: 280, price: 260 },
  { name: 'Turmeric (Luyang Dilaw)', category: 'spice', previous: 120, price: 126 },
  { name: 'Lemongrass (Tanglad)', category: 'spice', previous: 65, price: 62 },
];
